### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mateuszwu** [bartoszboruta/PandasFactory#1]
- [ ] Setup react with redux on webpack
- [ ] Setup ASP.NET MVC appliaction
- [ ] Setup NodeJs (express) API application
- [ ] Create database model
- [ ] Create SQL database
- [ ] Create readonly noSQL database
- [ ] Add Create/Login system - NodeJs
- [ ] Add Create/Login system - MVC
- [ ] Create CRUD for Post
- [ ] Create CRUD for Comment
- [ ] Create CRUD for Tag
- [ ] Create CRUD for Like
- [ ] Create CRUD for Category
- [ ] Create CRUD for User 
- [ ] Create CRUD for Blog
- [ ] Create search endpoint
- [ ] Add integration with Gravatar
- [ ] Add administrator permission to remove comments
- [ ] Add administrator righst to ban users and blogs
- [ ] Add administrator righst to manage category
- [ ] Create Blog component
- [ ] Create Post component
- [ ] Create Comment component
- [ ] Create Tag component
- [ ] Create User component
- [ ] Create Category component
- [ ] Create landing page 
- [ ] Create search page
- [ ] Add filters on landing page
- [ ] Add ability to upload image (for blog and post headers)
- [ ] Microservice to manage databases integration
- [ ] Create documentation
- [ ] Add specs

**Comment by mateuszwu** [comment]
- [ ] Add CreateBlog callback after user creation
- [ ] Add Edit blog routes
- [ ] Add upload image 
- [ ] Add showing post comments
- [ ] Add deleteing comments
- [ ] Styling
